# This config is an example of a 3-node cluster, each node has 16 cores and 3 SSD disks.
# YDB configuration options and their values
# are described in the documentaion https://ydb.tech/en/docs/deploy/configuration/config

static_erasure: mirror-3-dc

host_configs:
- drive:
  - path: /dev/disk/by-partlabel/ydb_disk_ssd_01
    type: SSD
  - path: /dev/disk/by-partlabel/ydb_disk_ssd_02
    type: SSD
  - path: /dev/disk/by-partlabel/ydb_disk_ssd_03
    type: SSD
  host_config_id: 1


hosts:
- host: ydb-node-zone-a
  host_config_id: 1
  location:
    body: 1
    data_center: 'zone-a'
    rack: '1'
- host: ydb-node-zone-b
  host_config_id: 1
  location:
    body: 2
    data_center: 'zone-b'
    rack: '2'
- host: ydb-node-zone-c
  host_config_id: 1
  location:
    body: 3
    data_center: 'zone-c'
    rack: '3'


domains_config:
  domain:
  - name: Root
    storage_pool_types:
    - kind: ssd
      pool_config:
        box_id: 1
        erasure_species: mirror-3-dc
        kind: ssd
        geometry:
          realm_level_begin: 10
          realm_level_end: 20
          domain_level_begin: 10
          domain_level_end: 256
        pdisk_filter:
        - property:
          - type: SSD
        vdisk_kind: Default
  state_storage:
  - ring:
      node: [1, 2, 3]
      nto_select: 3
    ssid: 1


channel_profile_config:
  profile:
  - channel:
    - erasure_species: mirror-3-dc
      pdisk_category: 0
      storage_pool_kind: ssd
    - erasure_species: mirror-3-dc
      pdisk_category: 0
      storage_pool_kind: ssd
    - erasure_species: mirror-3-dc
      pdisk_category: 0
      storage_pool_kind: ssd
    profile_id: 0


actor_system_config:
  use_auto_config: true
  node_type: COMPUTE
  cpu_count: 9


table_service_config:
  sql_version: 1


shared_cache_config:
  memory_limit: 12000000000
